package com.example.umc9th.domain.member.enums;

public enum Address {
    GANGSEO, YANCHEON, GURO, YEONGDEUNGPO, GEUMCHEON, GWANAK, DONGJAK, SEOCHO, GANGNAM, SONGPA, GANGDONG,
    GWANGJIN, JUNGNANG, NOWON, DOBONG, GANGBUK, SEONGBUK, DONGDAEMUN, SEONGDONG, JUNG,
    JONGNO, YONGSAN, MAPO, SEODAEMUN, EUNPYEONG
}
